### ISSUE TITLE
plugin cannot be run within docker

### ISSUE THREAD

**Issue by lesliechung88** [emqx/kuiper#170]
这种方式构建的so无法在docker apline上跑：
go build --buildmode=plugin -o plugins/sinks/Zmq.so plugins/sinks/zmq.go

我想到把上面加入到Makefile ,build时，报如下错误：
flag provided but not defined: -buildmode

能否有好的解决方法？谢谢

**Comment by jinfahua** [comment]
Can the command-line be run outside of Makefile in your env?

**Comment by lesliechung88** [comment]
命令行是可以运行的，并生成了so，需要安装了zeromq-4.2.2.tar.gz，并设置环境变量：
export PKG_CONFIG_PATH=/root/zmq/lib/pkgconfig 
就可以了正常执行如下命令了：
go build --buildmode=plugin -o plugins/sinks/Zmq.so plugins/sinks/zmq.go

ubuntu上生成的Zmq.so文件,拷入到apline docker 容器里，运行不了

**Comment by jinfahua** [comment]
We are preparing a document for how to build a plugin for Kuiper... Due to the Golang dynamic loading restrictions, a plugin that build from one systems, for most of cases, it cannot be run at another different systems. 

I would suggest you to build the plugin in your actual running environment, in your case, it should be ``apline docker``.

**Comment by lesliechung88** [comment]
@jinfahua thanks!

**Comment by jinfahua** [comment]
@lesliechung88 Please take a look at [this doc](https://github.com/emqx/kuiper/blob/develop/docs/zh_CN/plugins/plugins_tutorial.md) for how to develop Kuiper plugins.
