### ISSUE TITLE
Duplicate values SQL Query

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#255]
I'm trying to write an SQL Query against the demo stream to find if there are duplicate values of uint8 within a tumbling window.  Here's my query: SELECT uint8, count(*) FROM demo GROUP BY uint8 HAVING count(*) > 1, TUMBLINGWINDOW(ss, 10).  This is standard SQL for finding duplicates.  This gives me this error in kuiper: Parse SQL SELECT uint8, count(*) FROM demo GROUP BY uint8 HAVING count(*) > 1, TUMBLINGWINDOW(ss, 10) error: found ",", expected EOF..  After looking at the kuiper SQL (https://docs.emqx.io/kuiper/latest/en/sqls/query_language_elements.html), it seems this should be supported.  The document shows expressions are supported in SELECT..."Expression is a constant, function, any combination of column names, constants, and functions connected by an operator or operators."

**Comment by ngjaying** [comment]
@dmocek Your sql string has syntax error. The window clause should be a group by, not in having. And the count function requires a parameter.

`SELECT uint8, count(*) FROM demo GROUP BY uint8, TUMBLINGWINDOW(ss, 10) HAVING count(*) > 1`

You may also want to have an alias for count(*) so that it won't be calculated twice.
`SELECT uint8, count(*) as c FROM demo GROUP BY uint8, TUMBLINGWINDOW(ss, 10) HAVING c > 1`

**Comment by jinfahua** [comment]
> You may also want to have an alias for count(*) so that it won't be calculated twice.
> `SELECT uint8, count(*) as c FROM demo GROUP BY uint8, TUMBLINGWINDOW(ss, 10) HAVING c > 1`

Using alias for aggregation function now is not supported, opened a [new issue](https://github.com/emqx/kuiper/issues/260) for tracking this feature.

**Comment by dmocek** [comment]
Thanks, this solves my problem.
