### ISSUE TITLE
Cannot execute sample echo custom function in v0.4.2

### ISSUE THREAD

**Issue by dmocek** [emqx/kuiper#412]
I've followed the instructions for creating a custom function:
- https://github.com/emqx/kuiper/blob/master/docs/en_US/extension/function.md
- https://github.com/emqx/kuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md#docker-compiledocs/en_US/plugins/plugins_tutorial.md
using the echo function to test my setup.  I'm able to build Echo.so, but when I create my rule using it, I get this message:
`Parse SQL SELECT echo(temperature) FROM demo error: cannot get the plugin file name: invalid name echo: not exist.`
Here's what I've done:
- Checked out the kuiper repo (https://github.com/emqx/kuiper.git)
- Downloaded the emqx/kuiper:0.4.2 container, named it kuiper-dev, and run it
- Rund EdgeX Geneva (which runs emqx/kuiper:0.4.2-alpine
- Mounted my host kuiper directory to kuiper-dev
- cd to the kuiper directory
- Modify go.mod (per the documentation) to include:
`go 1.13
github.com/emqx/kuiper v0.0.0-20200323140757-60d00241372b`
- Run /usr/local/go/bin/go build -v --buildmode=plugin -o plugins/functions/Echo@v0.0.0.so plugins/functions/echo.go
- cp Echo@v0.0.0.so to emqx/kuiper:0.4.2:/kuiper/plugins/functions
- Create a rule using echo from the demo stream
`{
    "sql": "SELECT echo(temperature) FROM demo",
    "actions": [
        {
            "rest": {
                "method": "post",      
                "url": "http://10.159.142.91:8080/"
            }
        },
        {
            "log":{}
        }
    ]
}`

Note that I was able to successfully create and run my own custom rule using the EdgeX Foundry Fuji release (Kuiper v0.3.2), but the Geneva release (Kuiper v0.4.2) isn't working for me.

One interesting thing is that after I run the build command, go.mod and go.sum are changed.  1) go.mod no longer contains the emqx/kuiper entry I added above.  2) Both go.mod and go.sum are owned by root:root.  So it looks like the build process is changing these files.  In particular, I'm concerned about go.mod no longer containing the emqx/kuiper entry.

**Comment by ngjaying** [comment]
1. About the "invalid name echo: not exist" error, it seems like the plugin is not registered. Currently, to dynamically load a plugin, the plugin must be created by the REST API. Otherwise, if copying the .so file manually which mostly happens in developing, Kuiper must restart to load it.  So please restart Kuiper and try.

2. About the plugin build, did you run step 2 in the [plugin tutorial of docker compile](https://github.com/emqx/kuiper/blob/master/docs/en_US/plugins/plugins_tutorial.md#docker-compile), specifically the `# go mod edit -replace github.com/emqx/kuiper=/go/kuiper` command.  If you did, then the go.sum/go.mod should be changed you point it to a new location.

3. For echo plugin, it is part of the Kuiper project. To build it, you **don't** need to modify `go.mod` which is only needed when creating the plugin in a separated project. Just run the go build command to build it in the Kuiper project.

**Comment by dmocek** [comment]
Thanks, I have it working now.  Are you accepting suggestions for improving the documentation?

**Comment by jinfahua** [comment]
@dmocek Any suggestions will be appreciated :-)

**Comment by jinfahua** [comment]
Done & close the issue.
