### ISSUE TITLE
cannot get the plugin file path: invalid name edgex: not exist

### ISSUE THREAD

**Issue by untilbit** [emqx/kuiper#569]
I'm trying to connect kuiper to edgex 1.0.0.

After i create a stream of type edgex and a simple rule i get the follwoing error.

![image](https://user-images.githubusercontent.com/12769948/96872874-7795cd00-1474-11eb-9bd7-6f016ba00f6a.png)

I followed these steps.

1. Create a stream via api rest.

```
{
  "sql": "create stream events() WITH (FORMAT=\"JSON\", TYPE=\"edgex\")"
}
```

2. Create a rule via api rest.

```
{
  "id": "rule1",
     "sql": "SELECT * from events where temperature > 30",
   "actions": [
    {
      "mqtt": {
        "server": "tcp://127.0.0.1:1883",
        "topic": "result",
        "clientId": "demo_001"
      }
    },
    {
      "log":{}
    }
  ]
}
```

The rule post request returns this message:

![image](https://user-images.githubusercontent.com/12769948/96873245-fbe85000-1474-11eb-8456-78615c17eef4.png)

How can i fix the error I'm getting?

### Versions used
- Edgex version: 1.0.0 on armv7l
- Kuiper version: 0.9.1 and 1.0.0 for armv7l

**Comment by untilbit** [comment]
Version v1.0.0 has no plugins in:

https://www.emqx.io/downloads/kuiper-plugins/v1.0.0/debian/sources/

**Comment by jinfahua** [comment]
@untilbit It's recommended to use Docker version when you want to use Kuiper in EdgeX. The separated binary version of Kuiper does not include EdgeX source because EdgeX requires additional libraries. However, the library has already been included in Kuiper Docker image. 

If you'd like have a native Kuiper that supports EdgeX, you can build a native binary by yourself with command `make build_with_edgex`.

**Comment by jinfahua** [comment]
Done & close the issue.
